# Generated by Django 5.1.2 on 2024-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(db_default=None, null=True),
        ),
    ]
