# Generated by Django 5.1.2 on 2024-12-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='popularity',
        ),
    ]
